// SIDEBAR ACTIONS
export const TOOGLE_SIDEBAR = 'TOOGLE_SIDEBAR'

// PRODUCTS ACTIONS
export const TOOGLE_PRODUCTS_LOADING = 'TOOGLE_PRODUCTS_LOADING'
export const RESET_PRODUCTS = 'RESET_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCTS_ERROR = 'SET_PRODUCTS_ERROR'

// SINGLE PRODUCT ACTIONS
export const TOOGLE_PRODUCT_LOADING = 'TOOGLE_PRODUCT_LOADING'
export const RESET_PRODUCT = 'RESET_PRODUCT'
export const SET_PRODUCT = 'SET_PRODUCT'
export const SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR'

// PRODUCTS PAGE ACTIONS
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const TOGGLE_GRID_VIEW = 'TOGGLE_GRID_VIEW'
export const UPDATE_SORT = 'UPDATE_SORT'
export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const TOGGLE_CART_ITEM_AMOUNT = 'TOGGLE_CART_ITEM_AMOUNT'
export const CLEAR_CART = 'CLEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'
